### ISSUE TITLE
Problem with font-weight

### ISSUE THREAD

**Issue by reyalpsirc** [TOP-Chao/atom-react-native-css#10]
If I set this on CSS

```
font-weight: 600
```

or this

```
font-weight: "600"
```

I get errors running the App. The first one maps to `600` while the second one maps to `"\"600\""`.
Need a way to have it mapping to `"600"`.

The only solution so far to bypass this problem is:

```
font-weight: "JS('600')"
```

**Comment by 94cstyles** [comment]
The problem has been resolved, please update to the latest version.
