### ISSUE TITLE
Upgrade to 1.0.1 fails to install dependencies

### ISSUE THREAD

**Issue by rwuttke** [TOP-Chao/atom-react-native-css#12]
After upgrading to 1.0.1 to fix issue #11, I now get this error.

```
Error: spawn cmd.exe ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)
```

I tried restarting Atom in case it needed that restart to install, but to no avail.

Not sure if this is fully an atom issue or not.

**Comment by 94cstyles** [comment]
I do not have `win10` system. Unable to restore the situation that caused the error. Disabling plug-in options in the `Enable Sass file and install node-sass`, should not lead to mistakes. I need to install `win10` system to be tested again.

**Comment by rwuttke** [comment]
Yeah, it is weird, the previous version nicely installed the dependencies, so it is likely something in the newer versions of Atom that is causing the problem as well.

Works in Mac ONLY when node-sass is installed and then click that particular checkbox.

Same version as Windows 10, ie 1.7.1

**Comment by 94cstyles** [comment]
I use multiple win10 system computers, did not appear to your question, and now i do not know how to fix it.

**Comment by saiyanka** [comment]
Hello @rwuttke i'm new to atom (win 10) and i'm facing the same error, what do i need to do to make it disappear?

**Comment by rwuttke** [comment]
Uninstall it. I tried re-installing several times and kept getting the same error.
