### ISSUE TITLE
Support import Sass files

### ISSUE THREAD

**Issue by williambout** [TOP-Chao/atom-react-native-css#14]
Currently, the plugin doesn't work well with `@import` in scss files.
You have to save the scss file with `@import`in order to compile. (saving the imported file doesn't compile JS).

**Comment by 94cstyles** [comment]
I released a new version, to solve the problem submitted by you, thank you for your feedback.

**Comment by williambout** [comment]
Great work.
I just noticed that `JS()` values in imported scss are compiled as a string in the final JS file.
