### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by dev-xdyang** [TOP-Chao/atom-react-native-css#17]
Error: Command failed: /bin/sh -c find /Users/xdyang/Desktop/React Native/FirstIOSDemo/FirstIOSDemo -type f -name *.scss
find: Native/FirstIOSDemo/FirstIOSDemo: No such file or directory

**Comment by 94cstyles** [comment]
你问题问的是不是问错地方了。

**Comment by dev-xdyang** [comment]
这个问题是在使用该插件的时候出现。如果使用.scss，每次保存的时候就提示这个。如果是.css，就没有问题可以正常转换为.js的样式表。具体是那部分引起不是很清楚，所以来请教下！

**Comment by 94cstyles** [comment]
这里已经明显告诉你了`Native/FirstIOSDemo/FirstIOSDemo: No such file or directory` 没有找到目录~ 你把你插件的配置告诉我 我看你怎么写的。

**Comment by dev-xdyang** [comment]
直接使用Atom默认安装，没有自定义配置。No such file or directory这个错误只会在使用.scss文件的时候出现，在相同目录下面使用.css文件确能够正确转换出.js文件。

**Comment by 94cstyles** [comment]
当然了~ 因为编译sass文件会去找关联文件 执行了命令`find /Users/xdyang/Desktop/React Native/FirstIOSDemo/FirstIOSDemo -type f -name *.scss` 现在执行命令结果告诉你了 `No such file or directory` 没有找到目录 这么明显的问题 没看到么

**Comment by dev-xdyang** [comment]
算了，可能真的是个初级问题。我也是刚用这个，不是很明白里面的机制！还是要感谢你提供这个插件。
