### ISSUE TITLE
font-weight convert error

### ISSUE THREAD

**Issue by dev-xdyang** [TOP-Chao/atom-react-native-css#19]
the source .css file like this:
![2016-05-23 8 52 52](https://cloud.githubusercontent.com/assets/7471748/15471523/f57a6f62-2128-11e6-94ee-970c8fa111a6.png)
and converted .js file like this:
![2016-05-23 8 53 05](https://cloud.githubusercontent.com/assets/7471748/15471550/10a2f232-2129-11e6-9875-caecd9795ccf.png)
but I got a Error!
![simulator screen shot 2016 5 23 8 52 44](https://cloud.githubusercontent.com/assets/7471748/15471573/25286778-2129-11e6-9ca2-b62060e3d427.png)

And then I change converted .js file manual to:
![2016-05-23 8 53 28](https://cloud.githubusercontent.com/assets/7471748/15471610/692c312a-2129-11e6-8d93-362796e62c0b.png)
It's work fine, So I think maybe convert font-weight to string is correct!

My project package.json is:
{
  "name": "ComponentDemo",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "react": "^15.0.2",
    "react-native": "^0.26.1"
  }
}

**Comment by 94cstyles** [comment]
哎 ~ 你没有看过官方文档么 ~ font-weight 是枚举~ 你值应该写成 `font-weight: "600"` ~ 工具是死的 人是活的 ~

**Comment by dev-xdyang** [comment]
请问这个是有什么困难而致使不能在代码自动补全的时候直接给出正确提示，或者在转换的过程中完成相应的转换吗？这样插件也应该会更完美了一点！
