### ISSUE TITLE
Text Shadow Offset wrong compiled

### ISSUE THREAD

**Issue by petergerdes** [TOP-Chao/atom-react-native-css#2]
In the SCSS:
text-shadow-offset: "JS({width: 0, height: 0})";

In the JS:
"textShadowOffset": "\"JS({width: 0, height: 0})\""

It should be compiling this:
"textShadowOffset":{width: 0, height: 0}

React states that textShadowOffset cannot be a string.

**Comment by 94cstyles** [comment]
Your computer system?
I use mac os and windows tests are normal, you have described the problem occurs because the "js (...)" has not been parsed, and then I use your posted code successfully parsed.
Can you give me a complete code?

**Comment by petergerdes** [comment]
I'm running on the following setup:
- Mac OS 10.11.4
- Node v5.3.0
- react-native-css v1.2.35

I created a test.scss and ran: "react-native-css -i test.scss -o test.js", you can download the source and compiled js here: http://cl.ly/fUHV

**Comment by 94cstyles** [comment]
This is a very embarrassing thing, you are not using plugin I wrote `atom-react-native-css`,`react-native-css` does not support `JS()，vw，vh，vmax，vmin` These features are my extended。If you are using `atom`, you can use my plug.

**Comment by petergerdes** [comment]
Aaaahhh! Confusion! But thanks!
