### ISSUE TITLE
【Bug】 升级v1.1.1后有问题，padding和margin都出问题了！！！ 

### ISSUE THREAD

**Issue by donson** [TOP-Chao/atom-react-native-css#21]
![image](https://cloud.githubusercontent.com/assets/278913/15625748/6916b448-24e5-11e6-8dda-9a46c87eaed7.png)

请看看。。。

**Comment by 94cstyles** [comment]
好了，请更新。修复了其中一个Bug，结果导致了另外一个。严重失误。
