### ISSUE TITLE
auto modify files is confusing

### ISSUE THREAD

**Issue by apieum** [TOP-Chao/atom-react-native-css#28]
Hi,
your plugin looks amazing but it's quite confusing. 
Imagine I was starting a new reactJS (not react native) project and each time I was editing App.css, App.js was erased and replaced by the css formated by your plugin. It tooks me minutes to understand from where it cames (disabling each plugin one by one and restarting atom each time)

Wouldn't it be better to define a shortcut and disable auto editing by default ?

**Comment by 94cstyles** [comment]
plugin setting -> `Enable compile React Style` true or false
Controls whether to enable compile
