### ISSUE TITLE
装完插件后使用没反应的？

### ISSUE THREAD

**Issue by q351941406** [TOP-Chao/atom-react-native-css#29]
RT

**Comment by 94cstyles** [comment]
请提供ATOM版本和你插件的设置 最好能详细说明下

**Comment by q351941406** [comment]
atom版本最新，插件设置默认的，没动过，

**Comment by q351941406** [comment]
不是敲就会自动提示了吗

**Comment by 94cstyles** [comment]
哈? 你是说`atom-react-native-autocomplete`这个插件的问题?  这个插件好久没更新了 文档跟不上了 ~ 并且现在react-native 基本上是用es6语法开发的 提示的方式还是老的~ 目前不推荐使用了，因为一直在忙 所以没去更新它。
如果你实在要用，你确定右下角 文件的格式是否是 `javascript with JSX` 因为插件依托于 `language-javascript-jsx`

**Comment by q351941406** [comment]
其实我主要的问题是用atom写RN没有代码提醒，在StyleSheet.create写都没提醒。。特别蛋疼，
