### ISSUE TITLE
Is Your Plug-In Unexpectedly Generating New Files?

### ISSUE THREAD

**Issue by quadsurf** [TOP-Chao/atom-react-native-css#30]
Please see this issue:

https://github.com/facebookincubator/create-react-app/issues/518

I guess I'm the second person this is happening to, but I uninstalled your plug-in to see if that's what was causing it, and the problem persisted, which means that your plug-in is probably not at fault.

**Comment by 94cstyles** [comment]
I don't know, this plugin is for ` react-native ` use, does not support ` react `
