### ISSUE TITLE
Support for a CLI tool

### ISSUE THREAD

**Issue by kevnk** [TOP-Chao/atom-react-native-css#33]
It would be great to be able to use all the capabilities of this plugin but outside the context of atom. I would put it in my `package.json` scripts to watch for changes. This way you can offer more flexibility to users

If I were you, I would offer the ability to use all the options node-sass accepts and then any options your CLI tool would also need to accept.

**Comment by 94cstyles** [comment]
I'm sorry, the project has stopped maintenance.
