### ISSUE TITLE
Issue with font-family

### ISSUE THREAD

**Issue by williambout** [TOP-Chao/atom-react-native-css#4]
Hi,
When a font-family contains 'em' (like semibold), the plugin generates broken JS.

Example:
`font-family: ProximaNova-Semibold;` generates `"fontFamily": "ProximaNova-Sibold",`

**Comment by 94cstyles** [comment]
I do not understand the problem you describe.
`"fontFamily": ProximaNova-Sibold` This is not the result you want?
If you can use `font-family: "JS(ProximaNova-Semibold)";`
Or you want results  to tell me.

**Comment by williambout** [comment]
I want to have `"fontFamily": "ProximaNova-Semibold"` in my JS file.
I already tried `font-family: "JS(ProximaNova-Semibold)";` but it generates `"fontFamily": ProximaNova-Sibold`.

**Comment by 94cstyles** [comment]
I understand, I'll fix the problem within an hour.

**Comment by williambout** [comment]
Thanks :+1:

**Comment by 94cstyles** [comment]
Problem has been solved, please update.
