### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by williambout** [TOP-Chao/atom-react-native-css#7]
Hi,
I have severals errors :

`letter-spacing : .7px` is compiled into `"letterSpacing" : ".7px"` (should be 0.7 without px),
`margin-top: -20px` is compiled into `"marginTop": "-20px"` (should be 20 without px).

**Comment by taniald** [comment]
Same issue for me.

**Comment by 94cstyles** [comment]
The problem has been resolved, please update to the latest version.
