### ISSUE TITLE
The libsass binding was not found(win 10)

### ISSUE THREAD

**Issue by lejun** [TOP-Chao/atom-react-native-css#9]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.6.2
**System**: Unknown Windows Version
**Thrown From**: [atom-react-native-css](https://github.com/TOP-Chao/atom-react-native-css) package, v0.0.9
### Stack Trace

Uncaught Error: The `libsass` binding was not found in C:\Users\cc.atom\packages\atom-react-native-css\node_modules\node-sass\vendor\win32-ia32-46\binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.

```
At C:\Users\cc\.atom\packages\atom-react-native-css\node_modules\node-sass\lib\extensions.js:158

Error: The `libsass` binding was not found in C:\Users\cc\.atom\packages\atom-react-native-css\node_modules\node-sass\vendor\win32-ia32-46\binding.node
This usually happens because your node version has changed.
Run `npm rebuild node-sass` to build the binding for your current node version.
    at Object.sass.getBinaryPath (C:\Users\cc\.atom\packages\atom-react-native-css\node_modules\node-sass\lib\extensions.js:158:11)
    at Object.<anonymous> (C:\Users\cc\.atom\packages\atom-react-native-css\node_modules\node-sass\lib\index.js:16:36)
    at Module._compile (C:\Users\cc\AppData\Local\atom\app-1.6.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\cc\AppData\Local\atom\app-1.6.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\cc\AppData\Local\atom\app-1.6.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at compile.parseJSS (C:\Users\cc\.atom\packages\atom-react-native-css\lib\compile.js:47:77)
    at C:\Users\cc\.atom\packages\atom-react-native-css\lib\index.js:64:37
```
### Commands

```
     -3:44.8.0 core:save (atom-text-editor.editor.is-focused)
     -3:40.9.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  3x -3:40.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:38.6.0 core:save (atom-text-editor.editor.is-focused)
     -3:38.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:37 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:37 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:36.2.0 core:undo (atom-text-editor.editor.is-focused)
     -3:35.2.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -3:35 core:backspace (atom-text-editor.editor.is-focused)
     -3:34.5.0 core:save (atom-text-editor.editor.is-focused)
     -3:34.1.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -3:33.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:33.4.0 core:save (atom-text-editor.editor.is-focused)
     -3:32.7.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -3:32.5.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "atom-react-native-css": {
    "enableSass": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-react-native-autocomplete, v0.0.7
atom-react-native-css, v0.0.9
autocomplete-paths, v1.0.2
badass-react-snippets, v0.2.1
file-icons, v1.7.1
js-hyperclick, v1.4.1
language-babel, v2.17.0
language-javascript-jsx, v0.3.7
linter, v1.11.4
linter-eslint, v7.1.3
linter-xo, v0.13.0
react, v0.15.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

试了 这个[解决方法](http://stackoverflow.com/questions/29461831/libsass-bindings-not-found-when-using-node-sass-in-nodejs#),但还是提示相同错误。

**Comment by 94cstyles** [comment]
这是`node-sass`本身自己的问题，如果上面那方法解决不了，只能不用sass文件了。

**Comment by lejun** [comment]
谢谢。我试下 这个[方法](https://github.com/TOP-Chao/atom-react-native-css/issues/1)。

嗯，暂时时放弃sass,但是在 RN 的 JS 中写样式，不会自动提示？（只有在sass中会代码提示吗？）

**Comment by 94cstyles** [comment]
你可以使用`css`文件进行编辑样式，css文件也有提示。`atom-react-native-autocomplete`它可以让js中也有api和组件的提示。

**Comment by lejun** [comment]
嗯，好的。最近在的转RN，在IDE（webstorm,sublime）这一块耽误了很多时间（代码提示支持都不太完整）。试了你的 `atom-react-native-autocomplete` ，很强大。

是否有其他可以在JS内部提示样式的插件？
(看了sass的介绍，觉得也要纳入计划学习。)

**Comment by 94cstyles** [comment]
JS内部样式提示的没有吧~ 因为我是前端工程师 所以习惯用css来编辑rn样式。

**Comment by lejun** [comment]
css中的些关键词 
**例如**： `background-color`,但是 _RN_ 中的是 `backgroundColor`.之后需要特定的来修改吗？（我是androider）

**Comment by 94cstyles** [comment]
[看这个示例,css和scss编辑出来是一样的](https://github.com/TOP-Chao/atom-react-native-css#demo)

**Comment by lejun** [comment]
试了，很强大！！！
嗯，问题你可以关闭了。。。。

**Comment by lejun** [comment]
你可以把你atom中的 .eslintrc 配置粘贴出来吗？（生成的双引号）

> 下面是我项目中的
> 
> ``` bash
> module.exports = {
>   // I want to use babel-eslint for parsing!
>   "parser": "babel-eslint",
>   "env": {
>     // I write for browser
>     "browser": true,
>     // in CommonJS
>     "node": true
>   },
>    "globals": {
>         "React": true
>     },
>     "ecmaFeatures": {"jsx": true},
>   // To give you an idea how to override rule options:
>   "rules": {
>     "quotes": [2, "single"],
>     "eol-last": [0],
>     "no-mixed-requires": [0],
>     "no-underscore-dangle": [0]
>   },
>   "plugins":[
>   "react"
>   ]
> }
> ```

```
设置这个可以
>"quotes": [0, "single","avoid-escape"]
```

**Comment by 94cstyles** [comment]
什么意思，没懂? 这个文件哪里来的? ESLint的?
